---
- hosts: ansibleserver
  gather_facts: no
  tasks:
    - name: update ubuntu servers
      command: "sudo apt update"
    - name: Install python
      apt:
        name: python3
        state: present
    - name: Install docker python module
      pip:
        name: docker
    - name: Install docker
      apt:
        name: docker.io
        state: present
    - name: Start docker service
      service:
        name: docker
        state: started
