apiVersion: apps/v1
kind: Deployment
metadata:
   name: jyoti
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: jyoti
   template:
      metadata:
        labels:
          app: jyoti
      spec:
       containers:
        - name: jyoti
          image: jyotichaudhary90/static
          ports:
          - containerPort: 80
